name: SimpleWarpUI
version: 0.1.0
api: [3.0.0-ALPHA11]
main: SOFe\Tests\MosaicForms\SimpleWarpUI\SimpleWarpUI
depend: [SimpleWarp]

commands:
  warpui:
    description: Displays the SimpleWarp UI
    default: true
